name: btv
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.8
  - gfal2-util
  - numpy
  - pip:
    - law
    - order
    - uproot
    - uproot3
    - awkward
    - coffea
    - dask==2.21.0
    - git+https://github.com/dask/dask-jobqueue.git#egg=dask-jobqueue
    - git+https://github.com/tornadoweb/tornado.git#egg=tornado
